name: Autograding

on:
  push:
    branches:
      - main

jobs:
  testTwoDArrayOperations:
    name: Test 2D Array Operations Class
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Run TwoDArrayOperations tests
      run: ./gradlew test --tests "com.example.TwoDArrayOperationsTest"
